=== silvat0/TDS-AppVideo/AppVideo/xml/videos.xsd
<?xml version ="1.0" encoding ="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.tds.es/videos" xmlns="http://www.tds.es/videos"
	elementFormDefault="qualified">
	
	<xs:element name="videos">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="video" type="Video" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="Video">
		<xs:sequence>
			<xs:element name="URL" type="xs:string" minOccurs="1" maxOccurs="1" />
			<xs:element name="etiqueta" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute name="titulo" type="xs:string" use="required" />
	</xs:complexType>

</xs:schema>

=== silvat0/TDS-AppVideo/CargadorVideos-2/xml/videos.xml
<?xml version="1.0" ?>
<videos xmlns="http://www.tds.es/videos" xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
	xs:schemaLocation="http://www.tds.es/videos videos.xsd">
	
	<video titulo="Invasion">
		<URL><![CDATA[https://www.youtube.com/watch?v=DlaHxL3mHAU]]></URL>
		<etiqueta>Series</etiqueta>
		<etiqueta>AppleTV</etiqueta>
	</video>

	<video titulo="Radiohead - Lotus Flower">
		<URL><![CDATA[https://www.youtube.com/watch?v=cfOa1a8hYP8]]></URL>
		<etiqueta>Music</etiqueta>
		<etiqueta>Radiohead</etiqueta>
		<etiqueta>Electronic</etiqueta>
	</video>
	
	<video titulo="Technology Is Reinventing Humanity - Jordan Nguyen">
		<URL><![CDATA[https://www.youtube.com/watch?v=VxuWIXdYYyQ]]></URL>
		<etiqueta>Tech</etiqueta>
		<etiqueta>Speech</etiqueta>
	</video>

	<video titulo="House of Gucci">
		<URL><![CDATA[https://www.youtube.com/watch?v=eGNnpVKxV6s]]></URL>
		<etiqueta>Movie</etiqueta>
		<etiqueta>Cinema</etiqueta>
	</video>
	
	<video titulo="Arctic Monkeys - Do I Wanna Know?">
		<URL><![CDATA[https://www.youtube.com/watch?v=bpOSxM0rNPM]]></URL>
		<etiqueta>Music</etiqueta>
		<etiqueta>Artic Monkeys</etiqueta>
	</video>

</videos>

=== silvat0/TDS-AppVideo/AppVideo/xml/videos.xml
<?xml version="1.0" ?>
<videos xmlns="http://www.tds.es/videos" xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
	xs:schemaLocation="http://www.tds.es/videos videos.xsd">
	
	<video titulo="Invasion">
		<URL><![CDATA[https://www.youtube.com/watch?v=DlaHxL3mHAU]]></URL>
		<etiqueta>Series</etiqueta>
		<etiqueta>AppleTV</etiqueta>
	</video>

	<video titulo="Radiohead - Lotus Flower">
		<URL><![CDATA[https://www.youtube.com/watch?v=cfOa1a8hYP8]]></URL>
		<etiqueta>Music</etiqueta>
		<etiqueta>Radiohead</etiqueta>
		<etiqueta>Electronic</etiqueta>
	</video>
	
	<video titulo="Technology Is Reinventing Humanity - Jordan Nguyen">
		<URL><![CDATA[https://www.youtube.com/watch?v=VxuWIXdYYyQ]]></URL>
		<etiqueta>Tech</etiqueta>
		<etiqueta>Speech</etiqueta>
	</video>

	<video titulo="House of Gucci">
		<URL><![CDATA[https://www.youtube.com/watch?v=eGNnpVKxV6s]]></URL>
		<etiqueta>Movie</etiqueta>
		<etiqueta>Cinema</etiqueta>
	</video>
	
	<video titulo="Arctic Monkeys - Do I Wanna Know?">
		<URL><![CDATA[https://www.youtube.com/watch?v=bpOSxM0rNPM]]></URL>
		<etiqueta>Music</etiqueta>
		<etiqueta>Artic Monkeys</etiqueta>
	</video>
	
	<video titulo="OKAY LET'S GO">
		<URL><![CDATA[https://www.youtube.com/watch?v=AWM5ZNdWlqw]]></URL>
		<etiqueta>Comedia</etiqueta>
	</video>
	
	<video titulo="CALENTAMIENTO // Tráiler cinemático del episodio 4">
		<URL><![CDATA[https://www.youtube.com/watch?v=oZpULmDBvos]]></URL>
		<etiqueta>Game</etiqueta>
		<etiqueta>Riot</etiqueta>
		<etiqueta>Valorant</etiqueta>
	</video>
	
	<video titulo="EL LEGADO DE FIBONACCI">
		<URL><![CDATA[https://www.youtube.com/watch?v=PYk5lZEIlEk]]></URL>
		<etiqueta>Comedia</etiqueta>
		<etiqueta>Míster Jägger</etiqueta>
	</video>
	
	<video titulo="Animales lindos para cuando estás estresado">
		<URL><![CDATA[https://www.youtube.com/watch?v=ZuRLOlB4N8U]]></URL>
		<etiqueta>Animales</etiqueta>
		<etiqueta>Cute</etiqueta>
	</video>
	
	<video titulo="Zeri.exe">
		<URL><![CDATA[https://www.youtube.com/watch?v=t1PJ5kRXlxA]]></URL>
		<etiqueta>Game</etiqueta>
		<etiqueta>Riot</etiqueta>
		<etiqueta>LoL</etiqueta>
	</video>
	
	<video titulo="¿Qué pasaría si detonásemos a la vez todas las bombas nucleares?">
		<URL><![CDATA[https://www.youtube.com/watch?v=0NWLuj4j9mI]]></URL>
		<etiqueta>Curiosidades</etiqueta>
		<etiqueta>Mundo</etiqueta>
	</video>


</videos>
